---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flix-db-pv-claim
spec:
  storageClassName: {{ .Values.mysql_db_pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql_db_pvc.size }}