---

# Secret for database default/init user
apiVersion: v1
kind: Secret
metadata:
  name: flix-db-secrets
data:
  db-user: {{ .Values.mysqlDatabase.dbUser | b64enc }}
  db-password: {{ .Values.mysqlDatabase.dbPassword | b64enc }}
  root-passwd: {{ .Values.mysqlDatabase.rootDBpassword | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: flix-db-config
data:
  config.yaml: {{ toYaml .Values.flix.config | indent 2 | b64enc }}



